import pptxgen from 'pptxgenjs';
import type { SlideDeck, FlashcardSet, Quiz, NotesPack } from '../types.js';

export async function buildPptx(deck: SlideDeck): Promise<Buffer> {
  const pptx = new pptxgen();
  pptx.defineLayout({ name: 'WIDE', width: 13.33, height: 7.5 });
  pptx.layout = 'WIDE';

  // Title slide
  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: '1F41F5' };
  titleSlide.addText(deck.title, { x: 0.8, y: 2.6, w: 11.7, h: 1.4, color: 'FFFFFF', fontSize: 40, bold: true });
  if (deck.subtitle) titleSlide.addText(deck.subtitle, { x: 0.8, y: 4.0, w: 11.7, h: 0.8, color: 'D9E6FF', fontSize: 20 });

  for (const s of deck.slides) {
    const slide = pptx.addSlide();
    slide.background = { color: 'FFFFFF' };
    slide.addText(s.title, { x: 0.6, y: 0.5, w: 12.1, h: 1.0, color: '1B2A8F', fontSize: 28, bold: true });
    slide.addShape(pptx.ShapeType.line, { x: 0.6, y: 1.5, w: 12.1, h: 0, line: { color: '3563FF', width: 2 } });
    if (s.bullets.length) {
      slide.addText(
        s.bullets.map((b) => ({ text: b, options: { bullet: { code: '2022' }, breakLine: true, color: '1F2530', fontSize: 18 } })),
        { x: 0.8, y: 1.8, w: 11.7, h: 4.5 }
      );
    }
    if (s.notes) {
      slide.addText('Speaker notes: ' + s.notes, { x: 0.8, y: 6.4, w: 11.7, h: 0.8, color: '62718C', fontSize: 12, italic: true });
    }
  }

  const buf = (await pptx.write({ outputType: 'nodebuffer' })) as any;
  return Buffer.from(buf);
}

export function buildFlashcardsTsv(set: FlashcardSet): string {
  const esc = (s: string) => (s || '').replace(/\t/g, ' ').replace(/\n/g, ' ');
  const lines = set.cards.map((c) => `${esc(c.front)}\t${esc(c.back)}\t${esc((c.tags || []).join(' '))}`);
  return 'front\tback\ttags\n' + lines.join('\n') + '\n';
}

export function buildQuizCsv(quiz: Quiz): string {
  const esc = (s: string) => `"${String(s || '').replace(/"/g, '""')}"`;
  const header = 'question,type,option_a,option_b,option_c,option_d,answer,explanation,topic,difficulty';
  const rows = quiz.questions.map((q) => {
    const opts = [...q.options];
    while (opts.length < 4) opts.push('');
    const answer = q.type === 'mcq' ? String.fromCharCode(65 + q.answerIndex) : q.answer || '';
    return [
      esc(q.question),
      esc(q.type),
      esc(opts[0]),
      esc(opts[1]),
      esc(opts[2]),
      esc(opts[3]),
      esc(answer),
      esc(q.explanation),
      esc(q.topic || ''),
      esc(q.difficulty)
    ].join(',');
  });
  return header + '\n' + rows.join('\n') + '\n';
}

// ---- PDF (pdfkit) ----
export async function buildRevisionPdf(title: string, topics: { topic: string; practice?: string }[]): Promise<Buffer> {
  const PDFDocument = (await import('pdfkit')).default;
  const doc: any = new PDFDocument({ margin: 50 });
  const chunks: Buffer[] = [];
  doc.on('data', (c: Buffer) => chunks.push(c));
  const done = new Promise<Buffer>((resolve) => doc.on('end', () => resolve(Buffer.concat(chunks))));

  doc.fontSize(22).text(title, { underline: true });
  doc.moveDown();
  doc.fontSize(11).text(`Generated by StudyForge · ${new Date().toLocaleDateString()}`);
  doc.moveDown();
  topics.forEach((t, i) => {
    doc.fontSize(14).text(`${i + 1}. ${t.topic}`, { bold: true });
    if (t.practice) doc.fontSize(11).text(t.practice);
    doc.moveDown(0.4);
  });
  doc.end();
  return done;
}

// ---- Markdown notes ----
export function buildNotesMd(notes: NotesPack): string {
  const lines: string[] = [`# ${notes.title}`, ''];
  const sn = Array.isArray(notes.shortNotes) ? notes.shortNotes.join('\n\n---\n\n') : (notes.shortNotes || '');
  lines.push('## Short Notes', sn, '');
  lines.push('## Exam Notes', notes.examNotes || '', '');
  if (notes.quickTips?.length) {
    lines.push('### Quick Tips & Shortcuts', ...notes.quickTips.map((t, i) => `**Tip ${i + 1}:** ${t}`), '');
  }
  if (notes.diagrams?.length) {
    lines.push('### Diagrams', ...notes.diagrams, '');
  }
  if (notes.fiveMark.length) {
    lines.push('## 5-Mark Questions');
    notes.fiveMark.forEach((qa, i) => {
      lines.push(`### Q${i + 1}: ${qa.question}`);
      lines.push(qa.answer);
      if (qa.subtopics?.length) {
        lines.push('**Subtopics:**', ...qa.subtopics.map(st => `- ${st}`), '');
      }
      if (qa.diagrams?.length) {
        lines.push('**Diagrams:**', ...qa.diagrams.map(d => `- ${d}`), '');
      }
      if (qa.examples?.length) {
        lines.push('**Examples:**', ...qa.examples.map(e => `- ${e}`), '');
      }
      if (qa.keyPoints?.length) {
        lines.push('**Key Points:**', ...qa.keyPoints.map(k => `- ${k}`), '');
      }
      lines.push('');
    });
  }
  if (notes.tenMark.length) {
    lines.push('## 10-Mark Questions');
    notes.tenMark.forEach((qa, i) => {
      lines.push(`### Q${i + 1}: ${qa.question}`);
      if (qa.introduction) lines.push('**Introduction:**', qa.introduction, '');
      lines.push(qa.answer);
      if (qa.subtopics?.length) {
        lines.push('**Subtopics:**', ...qa.subtopics.map(st => `- ${st}`), '');
      }
      if (qa.diagrams?.length) {
        lines.push('**Diagrams:**', ...qa.diagrams.map(d => `- ${d}`), '');
      }
      if (qa.examples?.length) {
        lines.push('**Examples:**', ...qa.examples.map(e => `- ${e}`), '');
      }
      if (qa.keyPoints?.length) {
        lines.push('**Key Points:**', ...qa.keyPoints.map(k => `- ${k}`), '');
      }
      if (qa.conclusion) {
        lines.push('**Conclusion:**', qa.conclusion, '');
      }
      if (qa.markingScheme) {
        lines.push('**Marking Scheme:**', qa.markingScheme, '');
      }
      lines.push('');
    });
  }
  lines.push('## One-Page Summary', notes.onePage || '', '');
  if (notes.viva.length) {
    lines.push('## Viva Questions', ...notes.viva.map((q, i) => `${i + 1}. ${q}`), '');
  }
  return lines.join('\n');
}
